"""init migrate

Revision ID: 68263128f8a0
Revises: 
Create Date: 2024-01-11 11:10:56.342645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68263128f8a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_created')
        batch_op.drop_column('date_deleted')
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('date_deleted', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
