"""update users

Revision ID: ceda616d28f4
Revises: 68263128f8a0
Create Date: 2024-01-17 10:39:15.815347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceda616d28f4'
down_revision = '68263128f8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('access_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('expired', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('expired')
        batch_op.drop_column('access_token')
        batch_op.drop_column('password')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
